language: cpp
install: 
  - python test.py
  - git clone https://github.com/lanl/BEE.git
  - cd ./BEE
  - git checkout jieyang-dev
  - ./install.sh
  - export PATH=$(pwd)/bee-launcher:$PATH
  - export OS_AUTH_URL=https://chi.tacc.chameleoncloud.org:5000/v2.0
  - export OS_TENANT_ID=3e35a9401df74141b2e909ef1f28aef7
  - export OS_TENANT_NAME="CH-819321"
  - export OS_USERNAME="cjy7117"
  - export OS_PASSWORD="lanlBEE123"
  - openstack --version
  - cd examples/bee-launcher-example/flecsale/bee-os/
  - bee_ci_launcher.py -l flecsale
script: true
notifications:
  email: false
