language: cpp
install: 
# Install BEE for scalability test
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - git clone https://${GH_TOKEN}@github.com/lanl/BEE_Private.git && cd ./BEE_Private
  - git checkout jieyang-dev
  - ./install_on_travis.sh
  - export PATH=$(pwd)/bee-launcher:$PATH
  - echo $PATH
# Install other necesaary packages needed for the original CI
script: 
# Do original test.
# Push Docker image to DockerHub
# Compose beefile for scalability test with parameters (e.g., # of nodes)
# Do scalability test using VPIC as an example
  - cd examples/bee-launcher-example/flecsale2/bee-os/
  - travis_wait 120 bee_ci_launcher.py -l flecsale -r $OS_RESERVATION_ID
  - ls
  - /home/travis/build/cjy7117/test_travis_ci/output_parser.py
  - cp bee_scalability_test_parsed.output bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv
#  - touch scaliability_result_${TRAVIS_BUILD_NUMBER}.csv
  - mv bee_scalability_test_result_build_${TRAVIS_BUILD_NUMBER}.csv /home/travis/build/cjy7117/test_travis_ci/
  - cd /home/travis/build/cjy7117/test_travis_ci
  - ./BEE_Private/travis_ci/push_results_to_repo.sh
notifications:
  email: false
