language: cpp
install: 
  - git clone https://github.com/lanl/BEE.git
  - cd ./BEE
  - git checkout jieyang-dev
  - ./install.sh
  - export PATH=$(pwd)/bee-launcher:$PATH
  - bee_launcher.py
script: true
notifications:
  email: false
