language: cpp
install: 

  - git clone https://github.com/lanl/BEE.git
  - cd ./BEE
  - git checkout jieyang-dev
  - ./install.sh
  - export PATH=$(pwd)/bee-launcher:$PATH
script: 
  - cd examples/bee-launcher-example/flecsale/bee-os/
  - bee_ci_launcher.py -l flecsale -r $OS_RESERVATION_ID

notifications:
  email: false
